name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: andrw3/muebles-api:latest

  cloud-run:
    needs: docker
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"

      - uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/939479177252/locations/global/workloadIdentityPools/github/providers/my-repo"
          service_account: "939479177252-compute@developer.gserviceaccount.com"

      - name: Deploy to Cloud Run
        uses: GoogleCloudPlatform/github-actions/cloud-run@main
        with:
          service: muebles-api
          image: andrw3/muebles-api:latest
          region: us-central1
